# git-versioning main: user-conf

- type: application/vnd.org.wtwta.project
  main: user-conf
  id: user-conf
  slug-id: U-C
  version: 0.0.2-dev # user-conf
  vendor: dotmpe
  distribution: public
  license: GPL

  repositories:
    github: git@github.com:dotmpe/user-conf.git
    dotmpe.origin: git-repos/user-conf.git

  pd-meta:
    init: "./install-dependencies.sh project dev"
    check: ""
    test: "./tools/ci/test.sh"
    build: ""
    tasks:
      document: todo.txt

  lists:
    documents:
      exts: .rst

  # Usage `htd scripts run <script>`
  scripts:
    ci: # Builds the CI tests
      - git-versioning check
      - ./tools/git/hooks/pre-commit-spaceindent-check.sh '*'
      # FIXME setup or remove tab-check ./tools/git/hooks/pre-commit-tabindent-check.sh
      - eval $( hostname -s | tr 'a-z' 'A-Z' )_SKIP=1
      - ./tools/ci/test.sh

    init:
      - htd package update && htd package remotes-reset
      - vc regenerate

    test:
      - ./run-dev.sh ./bin/uc info
      #- ./run-dev.sh dash -lic '. ./bin/uc'
      #- htd run ci

    update:
      #- htd run ci-job-update
      - htd run job-update

    tasks:
      #- htd tasks --Check-All-Tags --Check-All-Files
      #- Check_All_Tags=1 Check_All_Files=1 htd tasks scan
      - radical.py -u todo.txt --excludes .git/info/exclude .

    build:
      - compo-seq c-groups tools -- tools-main generate > install-dependencies.sh
#
