jobs:
  build:

    # The start dir is ~/project, there is a helper to create the checkout
    docker:
      - image: dotmpe/treebox:edge

    steps:

    # Invoke CCI helper.
    - checkout

    - run:
        name: Setup
        command: |
          # XXX: not sure if these commands are executing in login-shell
          . ~/.profile
          # Prepare .test-env.sh file and overwrite ~/.profile
          . ./tools/ci/setup.sh
          { echo "# Added by $0:Setup on $(date --iso=min)"
            echo export scriptname=Circle-CI
          } >> ~/.profile
          # Log-profile needs a bit of special attention, check here
          #set -x
          . ./.test-env.sh
          echo shell-command: $0 $*
          echo shell-mode: $-
          echo shell-traps:
          trap
          echo Log: ${LOG:-unset}
          echo Init-Log: ${INIT_LOG:-}
          echo Sub-shell Log: $(bash -c 'echo \${LOG:-unset}')
          echo Sub-shell Init-Log: $(bash -c echo '\${INIT_LOG:-}')

    - run:
        name: Unit tests
        command: |
          . ./.test-env.sh
          . ./tools/ci/test.sh
          . ./tools/ci/convert.sh

    - run:
        name: Test
        command: |
          . ./.test-env.sh
          #. ./tools/ci/run.sh
          ./bin/uc info
          ./bin/uc init

    - store_artifacts:
        path: build/

    - store_test_results:
        path: build/

# Id: U-S:circleci/config.yml
