jobs:
  build:

    # The start dir is ~/project, there is a helper to create the checkout
    docker:
      - image: dotmpe/treebox:edge

    steps:

    # Invoke CCI helper.
    - checkout

    - run:
        name: Setup
        command: |
          #. ~/.profile
          . ./tools/ci/setup.sh
          { echo "# Added by $0:Setup on $(date --iso=min)"
            echo export scriptname=Circle-CI
          } >> ~/.profile

    - run:
        name: Unit tests
        command: |
          . ./test-env.sh
          ./tools/sh/log.sh notice foo bar baz
          ./tools/sh/log.sh warn foo bar baz
          ./tools/sh/log.sh error foo bar baz
          ./tools/sh/log.sh crit foo bar baz

          . ./tools/ci/test.sh
          . ./tools/ci/convert.sh

    - run:
        name: Test
        command: |
          . ./test-env.sh
          #. ./tools/ci/run.sh
          ./bin/uc info
          ./bin/uc init

    - store_artifacts:
        path: build/

    - store_test_results:
        path: build/

# Id: U-S:circleci/config.yml
