jobs:
  build:
    # Circle CI (base image):
    # The start dir is ~/project, there is a helper to create the checkout
    docker:
      - image: dotmpe/treebox:edge
    steps:

    # Invoke CCI helper.
    - checkout

    - run:
        name: Setup
        command: |
          . ~/.profile
          . ./tools/ci/setup.sh
          echo export scriptname=Circle-CI >> ~/.profile

    - run:
        name: Unit tests
        command: |
          . ./test-env.sh
          . ./tools/ci/test.sh
          . ./tools/ci/convert.sh

    - run:
        name: Test
        command: |
          . ./test-env.sh
          . ./tools/ci/run.sh

    - store_artifacts:
        path: build/

    - store_test_results:
        path: build/

# Id: U-S:circleci/config.yml
